# This is static page info for 404 and other error pages
- description: "Page not found (404) at University of Michigan Library. Return to the homepage, search by title/keyword, browse all Databases or Online Journals, or ask a librarian for assistance in locating resources."
  slug: "404"
  title: "404 - Page not found"
